src/components/MiradorViewer.js, src/pages/archives/ArchivePage.js
**Make mirador viewer options configurable and add default config.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2258) (:star:)
Make mirador viewer options configurable and add default config.
* Add default options to disable features in mirador that are broken and/or not being used
* Allow options to be overridden if they are defined in json config file
* start localhost server specifying iawa and using this config file: https://github.com/VTUL/VTDLP-siteconfig/blob/LIBTD-2258/configs/iawa.json
* View any "item" page and check that unneeded and/or broken features are disabled. 
* Top bar with "change layout" and "fullscreen" should be disabled. 
* "change layout", "side panel", and …
=> Make mirador viewer options configurable and add default config

amplify/backend/api/collectionarchives/schema.graphql, amplify/backend/function/collectionTitleEdit/collectionTitleEdit-cloudformation-template.json, amplify/backend/function/createCollectionHeirarchy/createCollectionHeirarchy-cloudformation-template.json, amplify/backend/function/createCollectionMap/createCollectionMap-cloudformation-template.json, amplify/backend/function/iawav2658176f3PostConfirmation/iawav2658176f3PostConfirmation-cloudformation-template.json, src/graphql/mutations.js, src/graphql/queries.js, src/graphql/schema.json, src/graphql/subscriptions.js, src/pages/collections/CollectionItemsLoader.js
**Refactor image grid to show images for collection and it's children.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2255) (:star:)
Refactor image grid to show images for collection and it's children.
* Adds `hierarchy_path` field to Archive table so that each archive will know all of the collections that it belongs to
* Updates query in CollectionItemsLoader.js to include the archives of a collections children as well.
* Changes can be viewed here: https://libtd-2255.djf1n0m63xbku.amplifyapp.com/
* Visit several collection show pages and check that image grid contains archives that belong to the current collection OR any of it's children.
* branch: `LIBTD-2255`
* After this PR is …
=> Refactor image grid to show images for collection and it's children

src/pages/collections/SubCollectionsLoader.js
**If the string ends in a number parse it and order by that.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2325) (:star:)
Sorts collections by ending number if present.
* Checks if collection titles end with a number that that can be parsed
* Sorts by those numbers if they exist
* Sorts alphabetically otherwise
* Visit IAWA collection show pages
* Check in hierarchy tree if the numbers are sorted correctly (1,2,3) instead of (1,10,11)
* branch: `LIBTD-2325`
@yinlinchen 
=> refactor collection hierarchy sort

cypress/integration/category_select_checkbox.spec.js, cypress/integration/multi_select_checkbox_spec.js, src/components/Collapsible.js, src/components/Pagination.js, src/components/Thumbnail.js, src/css/ListPages.css, src/css/SearchResult.css, src/lib/MetadataRenderer.js, src/pages/collections/CollectionItemsLoader.js, src/pages/collections/CollectionsListPage.js, src/pages/collections/CollectionsShowPage.js, src/pages/search/MasonryView.js, src/pages/search/SearchFacets.js, src/pages/search/SearchResults.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2324
Hides images which should be considered decorative, changes glyphs to font awesome icons so screen reader doesn't read them, adds aria-live sections to announce certain dynamic changes which include important messages, converts abbreviations for languages to the full word for each language in the search facets.
-Collapsible.js - adds additional argument to function call
-Pagination.js - conditionally renders aria roles/attributes for some elements, adds font awesome icons
-Thumbnail.js - conditionally inserts alt text
-ListPages.css - some CSS to integrate font awsome icons in pagination buttons
-SearchResult.css - some CSS for the new sections and icons
-MetadataRenderer.js - adds parameters and an if/else …
=> Accessibility fixes for WCAG 2.0

src/components/Breadcrumbs.js, src/lib/fetchTools.js, src/pages/collections/CollectionsShowPage.js, src/pages/collections/SubCollectionsLoader.js
**Refactor functions that iterate through heirarchy to use one query instead.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2328) (:star:)
Uses the new `heirarchy_path` field to refactor functions to use one query instead of an undetermined number of queries in an iteration. It simplifies the code and speeds up the application.
* adds `getTopLevelParentForCollection` to the fetchTools lib file and uses this in CollectionsShowPage.js and in SubCollectionsLoader.js
* adds `fetchHeirarchyPathMembers` to the fetchTools lib file and uses this in Breadcrumbs.js
* refactors code to work with these lib functions
* Visit collection show pages and check that:
* Collection hierarchy on right side …
=> Refactor functions that iterate through heirarchy to use one query

src/App.js, src/components/ContactSection.js, src/components/Header.js, src/components/HeaderBreadcrumbs.js, src/lib/CustomPageRoutes.js, src/lib/fetchTools.js, src/pages/AboutPage.js, src/pages/HomePage.js, src/pages/PermissionsPage.js, src/pages/admin/SiteAdmin.js, src/pages/admin/SiteForm.js, src/pages/archives/ArchivePage.js, src/pages/collections/CollectionsListLoader.js, src/pages/collections/CollectionsShowLoader.js, src/pages/search/SearchLoader.js
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2314) (:star:)
Amplify preview: https://libtd-2314.djf1n0m63xbku.amplifyapp.com/
This PR provides "edit/update" functionality to allow "SiteAdmin" users to modify site configurations using Amplify @auth. Currently, only two fields, "siteTitle" and "siteName" are editable. 
* schema.graphql: Add "Site" model with @key and @auth 
* amplify/backend/auth/userPoolGroups/user-pool-group-precedence.json: Change User groups' precedence to: Admin(1), Editor(2) and SiteAdmin(3) 
* src/pages/HomePage.js: Obtain siteTitle and siteName from DynamoDB table instead of config file 
* src/pages/admin/SiteForm.js:  Provide edit form for updating Site configurations
* Sign up as a "SiteAdmin" user and then go to "SiteAdmin" page to see if you can …
=> LIBTD-2314: Provide site configuration update function with amplify auth

src/App.js, src/components/MiradorViewer.js, src/pages/PermissionsPage.js, src/pages/archives/ArchivePage.js
Preview branch is deployed at: https://contact-fix.djf1n0m63xbku.amplifyapp.com/
This PR fixes the broken Permissions page due to failing to pass the site prop to ContactSection component.
* Adds site prop to ContactSection and MiradorViewer components
* Adds back the site.analyticsID in previous conflict merge
* Check if Permissions page is loaded properly 
* Check if Mirador viewer in an item display page works fine
Tag (@yinlinchen) interested parties
=> Fix broken contact section in permission page

README.md, cypress/integration/additional_pages.spec.js, package-lock.json, package.json
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2379) (:star:)
Upgrade Cypress to V5.5, so we can get rid of `-c experimentalShadowDomSupport=true` in the command line
1. pull LIBTD-2379 branch
2. npm install
3. run `CYPRESS_password=thepassword yarn run cypress open`
4. Also see the preview version of this deployment in Amply console `dlp-access-test` -> `LIBTD-2379`
=> upgrade cypress to 5.6

cypress/integration/admin_collectionpage_filter_sort_config.spec.js, cypress/integration/archive_media_views.spec.js, cypress/integration/collection_metadata_display.spec.js, public/index.html, src/components/Citation.js, src/components/MiradorViewer.js, src/css/ArchivePage.css, src/css/Viewer.css, src/pages/archives/ArchivePage.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2315
Changes IIIF viewer to Mirador which offers better accessibility features.
-Updates cypress test for mirador viewer
-Updates script to load viewer
-Revises viewer configuration and uses the new settings available for this version.
-changes a couple of CSS styles
-includes one unrelated fix for className in citation component. 
Viewer should show up on each archive page which has a manifest. If the object has multiple images, the thumbnails should show in a ribbon. All controls in Mirador 3 should be keyboard accessible by default.
Branch in LIBTD-2315
@yinlinchen 
=> Updated to Mirador 3

cypress/integration/archive_media_views.spec.js, src/components/MediaElement.js, src/css/ArchivePage.css, src/pages/archives/ArchivePage.js
**adds thumbnail representations for audio and video records.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2388) (:star:)
adds thumbnail representations for audio and video records
* Sets the "poster" attribute to the value of the item.thumbnail_image for video records
* Adds an additional div above audio player with img tag that renders with the item.thumbnail_image as it's source for audio records
* visit "/archive/m70xyh12" and check that static img is rendering as video placeholder
* visit "/archive/m69aah01" (or any of the other podcast items) and check that static img is rendering above audio player
* branch: `LIBTD-2388` …
=> adds thumbnail representations for audio and video records

src/components/MediaElement.js, src/pages/archives/ArchivePage.js
**Adds alt tag to audio record thumbnail img.**
* * *
Adds alt tag to audio record thumbnail img.
* Adds alt tag to audio record thumbnail img.
* Check any audio record show page, such as `/archive/m69xyh01`
* Right click on the thumbnail image and choose "Inspect"
* In dev tools check that the img element has a value for it's alt attribute
* branch: `fix_img_alt`
@yinlinchen 
=> add alt tag

cypress/integration/language_config.spec.js, src/lib/MetadataRenderer.js
**fix metadata renderer to support better testing.**
* * *
fix metadata renderer to support better testing
* Adds the metadata label as a class on the `tr` element so that we can query them by name in our tests. This is more reliable than querying for `:nth-child(n)` which can change if someone adds/removes a metadata entry
* Check that the metadata attributes on the archive and collection show pages are still rendering correctly
* Run the tests
* branch: `lang_test_fix`
@yinlinchen 
=> fix metadata renderer to support better testing

cypress/integration/archive_media_views.spec.js, package-lock.json, package.json, src/components/MtlElement.js, src/components/X3DElement.js, src/css/ArchivePage.scss, src/pages/archives/ArchivePage.js
**Adds support for rendering .x3d files.**
* * *
Adds support for rendering .x3d files 
* Loads x3dom js and css files dynamically (only when .x3d records are being viewed)
* Adds dom nodes to load and render .x3d files
* Visit `/archive/h387pp1c` and check that blister beetle 3d image is rendering correctly. (Note: this image does not match the record which is for "Amethyst."  Blister beetle was the only properly formatted, valid .x3d file that I could find so far.
* branch `color_3d`
@yinlinchen 
=> Adds support for rendering .x3d files 

cypress/integration/admin_homepage_collectionHighlights_config.spec.js, cypress/integration/admin_homepage_top_config.spec.js, src/pages/admin/BrowseCollectionsForm.js, src/pages/admin/ContentUpload.js, src/pages/admin/DisplayedAttributesForm.js, src/pages/admin/FileUploadField.js, src/pages/admin/HomepageForm.js, src/pages/admin/MediaSectionForm.js, src/pages/admin/SearchFacetsForm.js, src/pages/admin/SiteAdmin.js, src/pages/admin/SiteForm.js, src/pages/admin/SitePagesForm.js
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2371) (:star:)
This PR utilizes amplify dynamic group authorization rule to restrict site admins to access the admin page of their own site but not to the admin pages of other sites.
* pages/admin/SiteAdmin.js: On Site admin landing page, check if the signed-in user belongs to the siteAdmin group of this site to enable/disable access permission
* pages/admin/*Form.js: Add "groups" field to the newly created History record as only users belong to the corresponding siteAdmin group can create History records 
* Go to siteAdmin page of a repo, e.g., IAWA.
* Sign-in with a user belongs to the corresponding siteAdmin group: "iawaSiteAdmin", then "update" permission is guaranteed; if the user does not belong to the group, access to …
=> LIBTD-2371: Restrict site admins to access their own admin page only but not other sites' admin pages

src/lib/MetadataRenderer.js
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2407) (:star:)
This PR provides frontend adjustment in order to pick up the newly added "display_date" metadata field. To properly display the "date", we first try to use "display_date" metadata directly if it has value. Otherwise, we display the date using the format by concatenating three metadata fields: "circa", "start_date" and "end_date."
* Use "display_date" in date display as the first priority
* If no "display_date" field or "display_date" field has empty value, check "start_date"
* Go to SWVA application, see if date is displayed (updated) as expected especially for those with textual content
* Go to IAWA application, see if date is still displayed as previously formatted
Tag (@yinlinchen ) interested parties
(:star:) …
=> LIBTD-2407: Frontend adjustment for displaying date metadata

src/components/PodcastMediaElement.js, src/css/ArchivePage.scss, src/css/podcastMediaElement.scss, src/pages/archives/ArchivePage.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2099
wireframe - https://xd.adobe.com/view/518fe7b0-04fc-4066-a14d-c13bd8bb17c2-04dc/screen/822f3957-8c6a-4615-a651-605df08ab19b/
Creates a component to render the podcasts on archive pages.
-PodcastMediaElement - a customized media component that renders items from the podcast library. Changes styling and adds download button. Note that this component will also include a link to a transcript and links to other feeds for the show once that information is provided by the stakeholders.
-ArchivePage - implements PodcastMediaElement for the podcast library.
Podcasts should display in the customized podcast page and other audio/video …
=> Podcast media component and styles

src/components/KalturaPlayer.js, src/pages/archives/ArchivePage.js
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2433) (:star:)
This PR fixes Kaltura embed which originally does not pick up the unique entry_id for each video. Also for convenience, we use the video.vt.edu/media links instead of the rather long kaltura video links in our DynamoDB record.
* Changes the video link
* Uses entry_id to identify the video
* Go to hokies repo
* Go to archive/v2764b5m, check if video loaded properly
Tag (@yinlinchen) interested parties
=> LIBTD-2433: Pick Kalture video with specified entry_id

cypress/integration/archive_media_views.spec.js, src/components/CollectionTopContent.js, src/components/MediaElement.js, src/components/PodcastMediaElement.js, src/components/RelatedItems.js, src/components/Thumbnail.js, src/lib/fetchTools.js, src/pages/archives/ArchivePage.js
**Fetch assets using Storage.get to get url with auth creds where needed.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2447) (:star:)
Fetch assets using Storage.get to get url with auth creds where needed.
* Check if url requires auth creds.
* If so, use Storage.get to get url with creds
* If not, just return the url as is
* Visit the pages of our various sites (default, iawa, podcasts) and check if images, html files, and audio files are loading correctly
* LIBTD-2447
@yinlinchen 
=> Fetch assets using Storage.get to get url with auth creds where needed.

src/components/FileUploadField.js, src/css/adminForms.scss, src/pages/admin/ArchiveCollectionEdit/ArchiveForm.js, src/pages/admin/ArchiveCollectionEdit/CollectionForm.js, src/pages/admin/ArchiveCollectionEdit/ViewMetadata.js
**Add thumbnail upload to Archive edit form.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2457) (:star:)
Add thumbnail upload to Archive edit form.
* Adds `<FileUploadField />` component for thumbnail_path field
* visit "/siteAdmin" and click "Update Archive"
* Note the value in the "Thumbnail image" field so that you can change back to the original later
* Click "Edit" radio button and upload a new file using the "Thumbnail Image" field
* Submit the form and check that the record was successfully updated.
* (change the image back to what it was previously)
* branch: `LIBTD-2457`
@yinlinchen 
=> Add thumbnail upload to Archive edit form

src/pages/admin/SiteAdmin.js
**Add active classes to menu items on SiteAdmin page.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2478) (:star:)
Add active classes to menu items on SiteAdmin page.
* Checks which form has been selected
* Add "active" class to the menu item that matches them selected form
* Go to `/siteAdmin` page
* Click on several menu items and make sure that they stay highlighted when not hovering over them.
* branch: `LIBTD-2478`
@yinlinchen 
=> Add active classes to menu items on SiteAdmin page

src/pages/admin/ArchiveCollectionEdit/CollectionForm.js
**Set collection_category automatically, don't allow user modification.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2482) (:star:)
Set collection_category automatically, don't allow user modification.
* Removes `collection_category` form input field.
* Sets `collection_category` automatically using Site object if collection is new. (Should already be set if modifying an existing collection)
* Go to `/siteAdmin` and click "New / Update Collection"
* Create a new collection
* Check to make sure that the collection_category field is set correctly, according to the site you're logged in to
* branch: `LIBTD-2482`
@yinlinchen 
=> Set collection_category automatically, don't allow user modification.

src/lib/fetchTools.js, src/pages/search/SearchLoader.js
**Adjust fetchTools so that assetBasePath and lang fields can be removed from Site model.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2442) (:star:)
Adjust fetchTools so that assetBasePath and lang fields can be removed from Site model
* moves availableAttributes.json and language_codes_by_(name/abbr).json into bucket configured for site Storage
* Uses `Storage.get` to fetch files instead of using `lang` field
* visit "/siteAdmin" and click on "Displayed Attributes"
* check to make sure that attributes are loading
* visit "/search"
* check that Language filter is still working
* branch: `LIBTD-2442`
@yinlinchen 
=> Adjust fetchTools so that assetBasePath and lang fields can be removed from Site model

cypress/integration/search_bar.spec.js, src/lib/fetchTools.js
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2470) (:star:)
Change to matchPhrasePrefix, so user don't need to exactly query. e.g.  both `record` or `records` works. It is only for the `Title` in the search bar, as reported by the stakeholder.
1. See the amplify preview link below and do the search.
Tag (@tingtingjh ) interested parties
=> Change to matchPhrasePrefix

src/components/ContactSection.js
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2499) (:star:)
Remove Brackets and Commas from Email Display in About Pages
1. Pull & Run
2. See About page and check the change, should like screenshot above
=> Remove Brackets and Commas from Email Display in About Pages

src/css/AdditionalPages.scss, src/css/index.scss, src/pages/AdditionalPages.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2466
https://webapps.es.vt.edu/jira/browse/LIBTD-2467
Wen's feedback - https://docs.google.com/presentation/d/151ilRgro82BQAZxXF3pSZNU6nQB7s0fpPMnrpgn2a3I/edit?usp=sharing
Adds some based styles for fonts, links and tables to the additional pages included in digital libraries.
-CSS file for the styles
-Changes base font style to branded font for the site overall
-Adds class to component which generates these pages.
-SWVA additional pages should now look similar to the rest of the DLP. The tables should have improved spacing.
branch is LIBTD-2466
@yinlinchen 
=> Styles for additional pages

public/js/one.js, src/css/adminForms.scss, src/css/index.scss
https://webapps.es.vt.edu/jira/browse/LIBTD-2504
As noted in feedback from SWVA stakeholders, when the menu button is clicked and the navigation menu is expanded, the modal that covers the rest of the page content was not in the correct place.
The problem was that overflow:hidden was not being recognized on the html element by React. This style is now applied to body element successfully. So scrolling is disabled when the modal is active and without the scrollbar the modal placement is correct. I also corrected some small style conflicts that were impacting the modal/nav menu appearance.
Menu button should expand nav menu and modal to the left should appear with no gaps around it. The screen should not be scrollable.
Branch is LIBTD-2504
@yinlinchen …
=> Fixed placement of modal for VT branding

src/pages/admin/SiteForm.js
**Fix siteOptions bug that deletes requiredAttributes when the "General Site Config" form is submitted.**
* * *
Fix siteOptions bug that deletes requiredAttributes when the "General Site Config" form is submitted.
* Adds siteOptions to formState so that it can be saved correctly when "General Site Config" form is submitted.
* Change any value in the "General Site Config" form and submit changes.
* Check demo Site record in Dynamo to see if requiredAttributes object still exists in siteOptions field.
* branch: `fix_site_options`
@yinlinchen 
=> Fix siteOptions bug

cypress/integration/additional_pages.spec.js, src/App.js, src/components/Header.js, src/components/NavBar.js, src/css/index.scss
https://webapps.es.vt.edu/jira/browse/LIBTD-2503
Mockup: https://xd.adobe.com/view/4668a190-e56d-4bee-8689-e66e56da63ec-133b/.
Creates a navigation bar at the top of site pages for screen sizes over 992 px. At smaller screen sizes the hamburger menu will contain the navigation links. As per the Communications team, the button for the hamburger menu must be present at all screen sizes because it is part of the VT branding. The navigation bar is fully accessible. A submenu of links will appear on hover. The parent link is clickable. For keyboard users, the focus will move to the down arrow which opens the submenu on enter. The submenu allows in-menu navigation by arrow keys and …
=> Navigation bar

src/css/FeaturedItems.scss, src/css/RelatedItems.scss, src/pages/home/FeaturedItem.js, src/pages/home/FeaturedItems.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2391
Fixes display issue with featured items. After clicking on a panel with less than 4 items, the next panel would not show all the items that it was supposed to (i.e. on Demo site, click on dot for last panel, then click on dot for either of the other two panels and only one item would show eventhough those panels should show 4 items)
Changes the featured items component to display items based on adding an "active" property to items rather than by slicing the array.
FeaturedItems.scss & RelatedItems.scss - unrelated fixe for scaling when user changes browser settings to enlarge text.
FeaturedItem.js - adds conditional style
FeaturedItems.js - simplifies some code and adds function to add/update "active" …
=> Fix display of featured items

cypress/integration/admin_homepage_top_config.spec.js, src/css/FeaturedStaticImage.scss, src/css/HomePage.scss, src/css/adminForms.scss, src/pages/HomePage.js, src/pages/admin/HomepageForm.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2431
Removes the option from the admin site to hide the title of the digital library so that the cover image can have branded text included within the image. Also removes the code in the site which triggered the alternate layout and the cypress test for this feature. Due to accessibility concerns, this is not a good feature to support.
-cypress/integration/admin_homepage_top_config.spec.js -  just removes the test for changing the site to hide the title.
-FeaturedStaticImage.scss -  removes CSS for alternate layout
-HomePage.scss -  removes CSS for alternate layout
-adminForms.scss - removes CSS for the checkbox that was in the admin …
=> Removed code to hide title of library

src/components/CollectionMetadataSection.js, src/pages/collections/CollectionsShowPage.js
**Switch item and metadata sections for collections.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2541) (:star:)
Switch item and metadata sections for collections
* Move metadata block into it's own component
* Switch the order of the items block and the metadata block
* Launch the podcast site
* Visit one of the collection pages and check to see that the items block renders before (above) the metadata block
* branch: `LIBTD-2541`
@yinlinchen 
=> Switch item and metadata sections for collections

src/App.js, src/css/SiteSponsors.scss, src/css/colors.scss, src/pages/HomePage.js, src/pages/admin/HomepageForm.js, src/pages/home/SiteSponsors.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2538
https://apps.es.vt.edu/confluence/display/LIBTD/2021-10-29+Meeting+notes 
Adds customization options for the sponsors section on the homepage. Allows users to change the background color or the section, and choose whether the section will have a solid color background, or just a divider line in the color of their choosing.
-App.js - adds function to set css variable for background color
-siteSponsors.scss - adds needed css/classes
-colors.scss - adds css variable
-HomePage.js - adds style props
-HomePageForm.js - adds form to set sponsors section background color and style
-siteSponsors.js - adds conditional for class name
In …
=> Customizations for sponsors section

cypress/integration/admin_archive_edit.spec.js, cypress/integration/admin_collection_edit.spec.js, cypress/integration/admin_media_section_config.spec.js, src/components/NavBar.js, src/pages/admin/ArchiveCollectionEdit/EditMetadata.js, src/pages/admin/MediaSectionForm.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2544
Changes some inputs fields in admin site to text area fields to allow long text. Also updates tests that broke with this change.
-editMetadata and MediaSection forms have some inputs changed to textArea
The new textarea fields should allow users to update those section of the site the same way as the input fields did.
Branch is LIBTD-2544
@yinlinchen 
=> Input fields to TextArea

src/components/CollectionMetadataSection.js, src/css/CollectionsShowPage.scss, src/pages/collections/CollectionItemsList.js, src/pages/collections/CollectionItemsLoader.js, src/pages/collections/CollectionsListView.js, src/pages/collections/CollectionsShowPage.js, src/pages/collections/SubCollectionsLoader.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2547
Creates alternate layout for collection pages which displays collection items in a list rather than a grid
-CollectionMetadataSection.js - adjusts layout in a few ways
-CollectionsShowPage.scss - adds css to style list-view class, plus other adjustments
-CollectionItemsList.js - adds conditional and the code for list options versus default grid option
-CollectionItemsLoader.js - adjusts layout and adds required props
-CollectionsShowPage.js - adjusts layout and adds conditional to trigger collection list view component
-CollectionsListView.js - new component which creates the list view
-SubCollectionsLoader.js - just changes the …
=> List view for podcast collections

src/pages/collections/CollectionsShowPage.js
**Add key to collection metadata section to fix console warning.**
* * *
Add key to collection metadata section to fix console warning
Add key to collection metadata section to fix console warning
* Visit any collection show page and open the browser dev console
* Check that there are no warnings for missing keys. `Warning: Each child in a list should have a unique "key" prop.`
* branch: `fix_collection_key`
@yinlinchen 
=> Add key to collection metadata section to fix console warning

src/components/SortOrderDropdown.js, src/pages/collections/CollectionItemsLoader.js, src/pages/collections/CollectionsShowPage.js
**Allows podcast collection items to be sorted asc or desc.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2567) (:star:)
Allows podcast collection items to be sorted asc or desc.
* Add dropdown component to control sort order
* On change set sort order state in parent component
* Run query for items using sort_order state variable
* Visit a Podcast site collection page
* Make sure that the "Sort Order" dropdown is visible
* Toggle the values in the dropdown and check that the order of items changes accordingly
* branch: `LIBTD-2567`
@yinlinchen 
=> Allows podcast collection items to be sorted asc or desc

cypress/integration/admin_collection_edit.spec.js, src/components/CollectionTopContent.js, src/components/PodcastMediaElement.js, src/css/CollectionsShowPage.scss, src/css/podcastMediaElement.scss, src/lib/MetadataRenderer.js, src/pages/admin/ArchiveCollectionEdit/CollectionForm.js, src/pages/collections/CollectionsShowPage.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2548 
It adds form fields title podcast_link to the New/Update Collection area of the admin site. Users can enter links to podcast shows on various aggregators. The badge for that show will automatically populate on the collection's page in the DLP. The component supports 12 aggregators currently used by the stakeholder: Apple, Google, Spotify, Amazon, Stitcher, Breaker, Radio Public, Pocket Casts, TuneIn, Podchaser, Podbean, and Castbox.
-src/components/CollectionTopContent.js - adds all the logic needed to generate the correct badge from podcast_links and a link to the RSS feed.
-PodcastMediaElement.js - includes unrelated fix for …
=> Add feed links to collection page

src/components/CollectionTopContent.js, src/pages/admin/ArchiveCollectionEdit/CollectionForm.js
**adds rssLink to collectionOptions field in dynamoDb for podcasts.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2571) (:star:)
adds rssLink to collectionOptions field in dynamoDb for podcasts and uses that when rendering links on the collection show page
* Generates link to rss feed document in s3 when collection is created
* Saves link in `collectionsOptions` object field in Dynamo record
* Uses value saved in collection record for rendering "RSS Feed" link in collection show page
* Create a podcast collection
* Create a podcast episode in the newly created collection (RSS feed document is not generated until at least one episode is created)
* Visit collection show page and check …
=> adds rssLink to collectionOptions field in dynamoDb for podcasts

src/components/CollectionTopContent.js
**Looks for google.com matches in aggregator links. URL's can be case-sensitive.  Can't safely downcase them.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2575) (:star:)
Looks for google.com matches in aggregator links. URL's can be case-sensitive.  Can't safely downcase them.
* removes `.toLowerCase()` in aggregator links array
* Checks for "google.com" matches in addition to "goo.gl" to render "Google Podcasts" image
* Visit the show page for the "Stacks on Stacks" podcast "/collection/3h51gb9v"
* Check that the "Google Podcast" image renders correctly for the "google.com" link
* Check that the Spotify link correctly loads "Stacks on Stacks" on Spotify's site
* branch: `LIBTD-2575` …
=> Look for google.com matches in aggregator links, don't downcase urls

src/components/CollectionTopContent.js, src/css/CollectionsShowPage.scss
Fixes classes that weren't being applied to RSS badges. Corrects image for pocket casts.
-Image file src
-class style
On the collection page for MFAngle, the border activated on hover should match the shape of the badge. Pocket casts badge should now appear.
@yinlinchen 
=> Fixes podcast feed buttons

src/components/CollectionMetadataSection.js, src/components/SocialButtons.js, src/css/CollectionsShowPage.scss, src/css/SocialButtons.scss, src/pages/collections/CollectionsListView.js, src/pages/collections/CollectionsShowPage.js
* https://webapps.es.vt.edu/jira/browse/LIBTD-2557
Adds collapsible sections for social media sharing and collection details UI elements in the list view for collection pages. When the user's screen is full sized, these sections will automatically load as opened, and for smaller screen sizes these sections will automatically load as closed. This saves space in the mobile site and makes it easier to get the collection items. Collection pages that don't use the list view are not changed.
Adds an accordion element to the collectionListView component and changes necessary CSS.
Go to the collection page for any podcast. The elements should be open at full screen and closed for …
=> Adds collapsible sections

src/components/FileUploadField.js, src/components/PodcastMediaElement.js, src/css/ArchivePage.scss, src/pages/admin/PodcastDeposit.js, src/pages/admin/SiteAdmin.js, src/pages/archives/ArchivePage.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2421
Allows upload of transcript file in "Add podcast episode" of admin site.
Also aligns this component's presentation with the other components in the admin site.
Creates button and hidden display area in podcast item pages. 
FileUploadFiled.js - uploads text/plain files to "text" folder in S3
PodcastMediaElement.js - gets transcript file and displays it
PodcastDeposit.js - allows users to upload transcript file
SiteAdmin.js - fixes the display of the podcastDeposit component to match the other components.
ArchivePage.js - adds functionality for showing/hiding transcript
Create a new podcast episode and include an html file for a transcript. Navigate to that episode in the DLP and use the transcript button to …
=> Displays transcript file

src/components/FileUploadField.js, src/css/ArchivePage.scss, src/css/podcastMediaElement.scss, src/pages/admin/ArchiveCollectionEdit/ArchiveForm.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2579
Updates the archive form to allow transcripts to be added to existing audio and video files.
ArchiveForm.js - If the file is an audio or video file then the audioTranscript field is added to the editable fields. The field allows a file upload like the thumbnail field and those functions have been updated to work for both upload fields. When the form is submitted, the audioTranscript value is stored in archiveOptions.
Go to update item form in admin site and input any podcast identifier. Upload an html transcript. Then go to that item in the DLP and you should be able to display the transcript.
Branch is LIBTD-2579
@yinlinchen 
=> Add transcripts to existing podcasts

src/components/FormFields.js, src/css/adminForms.scss, src/lib/EmbargoTools.js, src/pages/admin/ArchiveCollectionEdit/CollectionForm.js
**Allows embargos to be attached to Collections.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2577) (:star:)
Allows embargos to be attached to Collections
* Adds form fields for embargo info to Collection form
* Creates or updates embargo record if at least one embargo date field is filled in
* Shows message indicating that embargo was NOT created if neither date field filled in (but still creates/updates collection record)
* Displays embargo info on collection admin "View" page
* Create a new Collection or edit an existing collection
* Fill out at least one of the embargo date fields
* Fill out the embargo note field
* After submitting changes the embargo details should be displayed …
=> Allows embargos to be attached to Collections

cypress/integration/admin_archive_edit.spec.js, cypress/integration/admin_page_title_config.spec.js, cypress/integration/podcast_deposit.spec.js, cypress/integration/related_items.spec.js, src/lib/EmbargoTools.js, src/pages/admin/ArchiveCollectionEdit/ArchiveForm.js, src/pages/admin/ArchiveCollectionEdit/CollectionForm.js
**Add ability to attach embargo to Archive records.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2577) (:star:)
Add ability to attach embargo to Archive records
* Adds embargo fields to Archive edit form
* Adds embargo info to admin Archive view
* Visit "Update Item" tab of /siteAdmin page
* Add or edit embargo info in edit form. At least one date must be added.
* Check that the embargo record has been created and that it's displayed in view
* branch: `LIBTD-2577_archives`
@yinlinchen 
=> Add ability to attach embargo to Archive records

src/components/MediaElement.js, src/components/PodcastMediaElement.js, src/css/ArchivePage.scss, src/css/podcastMediaElement.scss, src/pages/archives/ArchivePage.js
none
Allows media player to fetch .srt files so that captions can be used. Adds transcript section to non-podcast audio component.
-MediaElement.js - adds transcript section and ability to fetch audio and .srt files.
-PodcastMediaElement.js - adds ability to fetch .srt files
-ArchivePage.js - fixes function to generate filename for .srt files.
-CSS updates
non-podcast audio files should display transcript if one was uploaded. All audio files should fetch .srt files and player should show that captions can be turned on if .srt file is present.
Branch is fetchCaptions
@yinlinchen 
=> Fetches .srt files and displays transcripts

src/pages/admin/SiteForm.js, src/pages/collections/CollectionsShowPage.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2559
Adds settings in the admin site to allow users to choose grid or list layout and whether the grid of items will show above or below the metadata section.
-adds the settings to the SiteForm.js component.
-changing the settings will update the collection page in the live site.
branch is LIBTD-2559
@yinlinchen 
=> Adds collection page view option and items position

amplify/backend/api/collectionarchives/override.ts, amplify/backend/auth/iawav2658176f3/iawav2658176f3-cloudformation-template.yml, amplify/backend/auth/userPoolGroups/template.json, amplify/backend/function/iawav2658176f3PostConfirmation/iawav2658176f3PostConfirmation-cloudformation-template.json, amplify/backend/storage/Collectionmap/s3-cloudformation-template.json, amplify/team-provider-info.json, src/graphql/schema.json
**Sets ebsEnabled to true.**
* * *
OpenSearch requires config to explicitly enable EBS.
* Sets ebsEnabled to true in `amplify/backend/api/collectionarchives/override.ts`
* All other changes are a result of creating the `opendev` backend which I'm hoping will soon replace `newdev` and `dlpdev`
* Check that tests are passing an preview is generated
* Visually check over the preview site to make sure that nothing is broken.
* branch: `ebsEnabled`
@yinlinchen 
=> Sets ebsEnabled to true

cypress/integration/derivative_download_section.spec.js, src/components/Citation.js, src/components/DownloadLinks.js, src/components/LinkDropdown.js, src/css/DownloadLinks.scss, src/css/LinkDropdown.scss, src/lib/fetchTools.js, src/pages/archives/ArchivePage.js
**Renders download links on Archive show page (if they exist).**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2607) (:star:)
Renders download links on Archive show page (if they exist).
* Renders download links on Archive show page (if they exist).
* Fetches signed URL for each link so that it can be accessed from s3
* Visit "archive/s253n51s" in "Demo" site
* Check that download links exist in right column
* Check that download links function correctly
* Check that the image sizes are correct 
Example:
* …
=> Renders download links on Archive show page

cypress/integration/admin_searchpage_facet_sort_config.spec.js, cypress/integration/archive_metadata_display.spec.js, cypress/integration/language_config.spec.js, src/css/ListPages.scss, src/pages/admin/SiteAdmin.js
**display multi-valued field values on their own line.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2617) (:star:)
display multi-valued field values on their own line.
* Changes <span> to `display: block` so each will skip to a new line.
* Don't prepend a comma to each entry after the first
* Launch SWVA site
* Check that multi-valued fields are displayed correctly. Like this: https://libtd-2617.djf1n0m63xbku.amplifyapp.com/archive/0x56kb46 NOT like this: https://swva-pprd.cloud.lib.vt.edu/archive/0z43h83m
Example:
* branch: `LIBTD-2617`
@yinlinchen …
=> display multi-valued field values on their own line

src/App.js, src/components/CollectionTopContent.js, src/components/DownloadLinks.js, src/components/FileUploadField.js, src/components/MediaElement.js, src/components/PodcastMediaElement.js, src/components/Thumbnail.js, src/lib/FileGetter.js, src/lib/fetchTools.js, src/pages/AboutPage.js, src/pages/AdditionalPages.js, src/pages/HomePage.js, src/pages/PermissionsPage.js, src/pages/admin/ArchiveCollectionEdit/ArchiveForm.js, src/pages/admin/ContentUpload.js, src/pages/admin/PodcastDeposit.js, src/pages/admin/SitePagesForm.js, src/pages/archives/ArchivePage.js, src/pages/home/CollectionHighlights.js, src/pages/home/SiteSponsors.js
**Refactor the FileGetter class to allow removal of Storage.configure() calls that can cause a race condition.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2643) (:star:)
Multiple async fetches from multiple components at the same time can cause a race condition when they're all trying to set the s3 "public prefix" attribute by calling Storage.configure(). This PR sets the prefix to "" (empty string) once in `App.js` and then each fetch request just includes the prefix in it's "s3 key"
* Removes Storage.configure() calls throughout application which can conflict
* Adds ONE Storage.configure() call in `App.js` that sets public prefix to "" (empty string)
* Refactors FileGetter class to …
=> Refactor the FileGetter class to allow removal of Storage.configure() calls.

amplify/backend/api/collectionarchives/schema.graphql, src/graphql/mutations.js, src/graphql/queries.js, src/graphql/schema.json, src/graphql/subscriptions.js, src/lib/available_attributes.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2659
-New fields were documented in the "For developers only" tab of this spreadsheet: [](https://docs.google.com/spreadsheets/d/1UK1ekAsmtj5KyLeKFv-EAhgl-xSBQeGQ6bXViR0Myag/edit#gid=632902402) 
-documentation has been update here: [](https://github.com/VTUL/dlp-access/wiki/VTDLP-Metadata-Elements)
Adds the new elements to schema.graphql.
Adds elements to list of available attributes to be displayed in the UI
If metadata for these fields is ingested, then it can be edited and displayed through the app.
**This requires using the testingest backend
-A test item already exists - bhsst001001. This item has a value for all the new fields. …
=> Adds new metadata elements

src/lib/fetchTools.js, src/pages/AboutPage.js
**Fetch html documents as blob. Set's download to true so it returns an object with the file body instead of a Signed URL**
* * *
Fetch html documents as blob. Set's download to true so it returns an object with the file body instead of a Signed URL*
* Fetch html documents as blob. 
* Set's download to true so it returns an object with the file body instead of a Signed URL
* visit `/about` and `/permissions` in the generated preview and check to see that page content is loading and rendering.
* A bunch of the links in the site records for these "additional pages" aren't compatible w/ the current fetch methods. (Some of the links are just filenames w/ no path) I've fixed the …
=> fetch html documents as blob

cypress/integration/admin_csvExport.spec.js, cypress/integration/admin_page_upload_file.spec.js, src/css/adminForms.scss, src/pages/admin/ContentUpload.js, src/pages/admin/MetadataUpload.tsx, src/pages/admin/SiteAdmin.js
**Provides upload interface for metadata docs (csv format).**
* * *
**JIRA Ticket**: ([link](https://webapps.es.vt.edu/jira/browse/LIBTD-2625)) (:star:)
Provides upload interface for metadata docs (csv format). Renames file depending on record type before writing to s3 bucket so that s3toDDB lambda function will know how to process the file.
* Allows user to indicate if records are for Archives or Collections
* Allows user to upload their metadata to browser memory
* Renames csv file depending on whether it contains Archive records or Collection records
* Writes csv file to the s3 bucket that is configured to …
=> Provides upload interface for metadata docs

amplify/backend/api/collectionarchives/schema.graphql, amplify/backend/types/amplify-dependent-resources-ref.d.ts, amplify/team-provider-info.json, cypress/integration/admin_archive_edit.spec.js, cypress/integration/admin_collection_edit.spec.js, cypress/integration/admin_homepage_top_config.spec.js, cypress/integration/admin_page_sitepages_config.spec.js, package-lock.json, package.json, src/components/Citation.js, src/components/Editor.js, src/components/MediaElement.js, src/components/PodcastMediaElement.js, src/css/Editor.scss, src/css/SiteAdmin.scss, src/css/adminForms.scss, src/graphql/mutations.js, src/graphql/queries.js, src/graphql/schema.json, src/graphql/subscriptions.js, src/lib/MetadataRenderer.js, src/lib/fetchTools.js, src/pages/AboutPage.js, src/pages/AdditionalPages.js, src/pages/PermissionsPage.js, src/pages/admin/ArchiveCollectionEdit/ArchiveForm.js, src/pages/admin/ArchiveCollectionEdit/CollectionForm.js, src/pages/admin/ArchiveCollectionEdit/EditMetadata.js, src/pages/admin/HomepageForm.js, src/pages/admin/SitePagesForm.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2661
This adds WYSIWYG editor to the parts of the admin site that accept html content (HomepageForm, SitePagesForm, and the forms for editing archives and collections (EditMetadata). It also adds a new PageContent table to store the html for site pages. It also updates the places throughout the site so that HTML is rendered correctly.
- src/components/Citation.js - just a small change to parse the html using the same tool consistently.
- src/components/Editor.js - the component for the WYSIWYG editor, which is called Quill. The modules prop defines which options to display in the toolbar. The formats prop defines what html elements can be copied and pasted in the text editing area. …
=> HTML Editor

cypress/integration/archive_media_views.spec.js, src/components/GalleryView.js, src/components/ItemListView.js, src/components/MinervaPlayer/MinervaPlayer.tsx, src/components/Thumbnail/Thumbnail.tsx, src/components/Thumbnail/thumbnail.test.js, src/css/ArchivePage.scss, src/css/Viewer.scss, src/pages/archives/ArchivePage.js, src/pages/collections/CollectionsShowPage/CollectionItems.tsx, src/pages/collections/CollectionsShowPage/tests/collection-top-content.test.js, src/pages/search/ItemsList.js, src/pages/search/MasonryView.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2673
Styles the minerva viewer component
-MinervaPlayer.tsx - makes some semantic changes (links to buttons), adds a link around the image, makes some adjustments to typescript stuff.
-thumbnail, galleryview, itemlistview, masonryview, itemslist, collectionitems - removes unnecessary label props for thumbnail component.
Styles should be visible in minerva item in the Demo collection. Check that the buttons work same as the links did.
branch is LIBTD-2673
@whunter 
=> Minerva viewer styles

src/components/MinervaPlayer/MinervaPlayer.tsx, src/css/Viewer.scss
**Hide channel groups section in Minerva player.**
* * *
Hide channel groups section in Minerva player
* adds "display:none" to `.minerva-root .minerva-legend` class to hide the Channel Groups section
* Visit preview site (I'll put the link here when it finishes deploying): https://remove-pws-channels.d234tdmg9icdwk.amplifyapp.com/archive/8919df16
* The Minerva player should look like this (no Channel Groups interface on right side):
* branch: `remove_pws_channels`
@goynejennifer 
=> Hide channel groups section in Minerva player

package-lock.json, package.json, src/pages/search/SearchResults.js
**Fix bug relating to tags not having predefined labels.**
* * *
**JIRA Ticket**: (None, sorry) (:star:)
Fixes bug relating to tags not having predefined labels. Tags are not included in "search facets" because they are defined IN the metadata and can't be predefined with an associated label. So the label for ANY tag should be "Tag". Actual facets should continue to render their labels as defined.
This PR also includes an update to `package.json` to address a bug caused by competing versions of `react-refresh`
* Adds a function to SearchResults.js to handle separate case for tag label in addition to facet case …
=> Fix bug relating to tags not having predefined labels
