VTUL/dlp-access

src/components/Collapsible.js, src/lib/fetchTools.js, src/pages/search/SearchFacets.js, src/pages/search/SearchLoader.js
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2304) (:star:)
https://webapps.es.vt.edu/jira/browse/LIBTD-2305, which adds the third collection titled "Leonard J. Currie Slides."
Amplify preview: https://libtd-2304.djf1n0m63xbku.amplifyapp.com
This PR adds "Collection" search facet functionality into SWVA application.
* Adds "parent_collection" search filter in lib/fetchTools.js
* Adds getCollectionIDByTitle in lib/fetchTools.js
* Adds "Collection" filter in searchFacets.js and searchLoader.js
* Wait until PR for https://webapps.es.vt.edu/jira/browse/LIBTD-2305 is merged
* In SWVA application, go to "SEARCH" page, test out the second "Collection" filter functionality
Tag (@yinlinchen ) …
=> LIBTD-2304: Collection search facet for SWVA

src/pages/collections/CollectionsShowPage.js
**handle edge case where collection has no hierarchy.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2322) (:star:)
handle edge case where collection has no hierarchy
* Returns 0 if subcollections == null instead of trying to return subcollections.length and breaking
* Check http://localhost:3000/collection/8j19xh9q and http://localhost:3000/collection/9z04mz15 and make sure that they render correctly without errors
* branch: `LIBTD-2322`
@yinlinchen 
=> handle edge case where collection has no hierarchy

package-lock.json, package.json, src/css/SearchResult.css, src/pages/search/SearchFacets.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2312
amplify preview: 
https://libtd-2312.djf1n0m63xbku.amplifyapp.com/
The PR manages the focus for modal that displays the search filters on smaller sized screens. Focus is locked within the modal, the user can escape the modal by hitting escape, and focus resets to the button that activates the modal after it is closed.
-adds react-focus-lock package which is used to create the lock layer
-adds event listener for escape key when modal is active
-automatically moves focus to modal when active
User should be able to tab through all the controls in the modal, close the modal using escape key, and being tab sequence at filter button after closing the modal.
branch is LIBTD-2312
@yinlinchen 
(:star:) Required …
=> Modal accessibility

amplify/backend/api/collectionarchives/schema.graphql, amplify/backend/function/collectionTitleEdit/collectionTitleEdit-cloudformation-template.json, amplify/backend/function/createCollectionHeirarchy/createCollectionHeirarchy-cloudformation-template.json, amplify/backend/function/createCollectionMap/createCollectionMap-cloudformation-template.json, amplify/backend/function/iawav2658176f3PostConfirmation/iawav2658176f3PostConfirmation-cloudformation-template.json, src/graphql/mutations.js, src/graphql/queries.js, src/graphql/schema.json, src/graphql/subscriptions.js, src/pages/collections/CollectionItemsLoader.js
=> Revert "Refactor image grid to show images for collection and it's children"

cypress/integration/related_items_spec.js, package-lock.json, package.json, src/components/RelatedItems.js, src/css/RelatedItems.css, src/pages/archives/ArchivePage.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2152
Creates a section for Related items which will show at the bottom of the archive page. This section first searches for other items in the same subcollection. If there are less than ten, then it will search for items in the direct parent collection of this subcollection, and the items from the other subcollections of the parent collection. Once it finds 10 items total it will stop building a list and display the results. If it doesn't find 10 items, then it will return whatever number of items were found. If no other items are found then then section won't show.
-related_items_spec.js - cypress test for this component
-package.json - the carousel relies on two npm packages, react-slick and slick-carousel …
=> Created Related Items section

src/components/Citation.js, src/components/RelatedItems.js, src/css/ArchivePage.css, src/css/Citation.css, src/css/CollectionsShowPage.css, src/css/RelatedItems.css, src/lib/MetadataRenderer.js, src/pages/archives/ArchivePage.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2332
Mockup: https://xd.adobe.com/view/02fc158b-3aaa-4619-671b-65852af58b64-74cd/screen/8092deb2-f4f0-40dc-849c-a1c1a3aa5252/
Creates a section on the archive pages for citation information. Currently, it is only populated with the permanent link, but more citation information will be added in future iterations.
-creates a citation component and makes some adjustments to other sections for layout and headings hierarchy. Also appended "https://" to the permanent link formatting.
-on the archive page, the citation section should show above the metadata table. It should be populated with the permanent link, and a hint box should show …
=> Citation section

cypress/integration/related_items_spec.js
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2352) (:star:)
This PR fixs the related_items_spec test, which was unable to be passed if run all the tests at once in local
Pull the PR and run cypress and test all test cases at once.
See the [LIBTD-2352](https://webapps.es.vt.edu/jira/browse/LIBTD-2352) description to reproduce this issue
=> fix related_items_spec test

README.md, cypress/integration/authenticator_spec.js
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2353) (:star:)
Add an initial auth cypress test so tickets in LIBTD-2263 can add tests
Use `yarn run cypress open -c experimentalShadowDomSupport=true` to run all the test cases
=> Add auth signin singout test

cypress/integration/siteAdmin_contact_config.spec.js, src/components/ContactSection.js, src/pages/AboutPage.js, src/pages/admin/Contacts.js, src/pages/admin/SiteForm.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2334
Adds contact config fields to admin site
Adds contact array to state, adds all the fields for both contacts to the site form, adds a new function to update the content of these fields, the contact data is formatted before submitting the update for the site. PR lso includes a cypress test to show that it is working. 
For any site, if you enter the site admin page and click on "Edit Site" then edit the content of a contact field, the field's content will dynamically be stored in "formState". When the "Update Form" button is clicked, the new content will show in the "View Site" page and it will be written to the DynamoDB table.
Branch is LIBTD-2334
@yinlinchen 
=> Contact config for admin site

cypress/integration/admin_homepage_top_config.spec.js, src/css/adminForms.css, src/pages/admin/FileUploadField.js, src/pages/admin/HomepageTop.js, src/pages/admin/SiteAdmin.js
**Admin config for homepage statement and static image.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2341) (:star:)
Adds form to allow admins to edit the config for the homepage statement and the homepage static image.
* Adds form to allow admins to edit the config for the homepage statement and the homepage static image
* Records actions to history table in dynamo.
* visit `/siteAdmin`
* click `Homepage Top Config`
* Change values in fields and submit
* Check that changes are reflected in "view" page.
* branch: `LIBTD-2341`
@yinlinchen 
=> Admin config for homepage statement and static image

src/components/Citation.js, src/components/RelatedItems.js, src/css/AboutPage.css, src/css/Citation.css, src/css/CollectionHighlights.css, src/css/CollectionsListPage.css, src/css/CollectionsShowPage.css, src/css/FeaturedItems.css, src/css/ListPages.css, src/css/RelatedItems.css, src/pages/AboutPage.js, src/pages/collections/CollectionsListPage.js, src/pages/home/CollectionHighlights.js, src/pages/home/FeaturedItems.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2364
Changes all headings that were previously styled with the highlight color to black.
Heading in the citation section, related items, About page, collection highlights, and the collections pages have been changed to black.
All the heading should be black
Branch is LIBTD-2364
@yinlinchen 
=> Changed headings to black

src/App.js, src/components/Header.js, src/components/MiradorViewer.js, src/components/SiteNavigationLinks.js, src/lib/CustomPageRoutes.js, src/lib/fetchTools.js, src/pages/AboutPage.js, src/pages/AdditionalPages.js, src/pages/HomePage.js, src/pages/PermissionsPage.js, src/pages/archives/ArchivePage.js, src/pages/collections/CollectionsListLoader.js, src/pages/collections/CollectionsShowPage.js, src/pages/search/SearchLoader.js, src/pages/search/SearchResults.js
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2373) (:star:)
1. Remove all siteDetails
2. Use site, which is pull data from the DynamoDb `site` table
1. Local test
2. See it in the Amplify preview
=> remove all siteDetails

cypress/integration/admin_page_searchfacets_config.spec.js, src/components/Collapsible.js, src/css/adminForms.css, src/pages/admin/SearchFacetsForm.js, src/pages/admin/SiteAdmin.js, src/pages/search/SearchFacets.js
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2336) (:star:)
This PR allows a siteAdmin user to edit search facets related configurations for the application site. It limits the modifications on the values of category and date facets though. However, their labels are still configurable. The authorized user can add/delete a facet field as well as add/delete a label or a specific value for a facet field. The configuration changes will reflect on the Search page of the application site.
* Adds detailed tests for add/delete/update facet field and its label and values
* Adds the edition form/functionality for add/delete/update facet field and its label and values
* Reflects label change on the application search facet section
* Go to /siteAdmin, click on "Search Facets config" …
=> LIBTD-2336: Site Admin Search Facets configurations

cypress/integration/admin_homepage_top_config.spec.js
**use check and uncheck instead of click for checkboxes.**
* * *
use check and uncheck instead of click for checkboxes so that the test does not depend on the state of the db.
* use check and uncheck instead of click for checkboxes
* run tests and confirm that `admin_homepage_top_config.spec.js` passes
* branch: `fix_homepage_tests`
@yinlinchen 
=> use check and uncheck instead of click for checkboxes

cypress/integration/additional_pages.spec.js, cypress/integration/admin_homepage_top_config.spec.js, cypress/integration/admin_page_contact_config.spec.js, cypress/integration/admin_page_searchfacets_config.spec.js, cypress/integration/admin_page_sitepages_config.spec.js, cypress/integration/admin_page_upload_file.spec.js, cypress/integration/archive_metadata_display.spec.js, cypress/integration/browse_collections.spec.js, cypress/integration/category_select_checkbox.spec.js, cypress/integration/collection_metadata_display.spec.js, cypress/integration/filter_collections.spec.js, cypress/integration/linked_metadata.spec.js, cypress/integration/multi_select_checkbox_spec.js, cypress/integration/search_bar.spec.js, cypress/integration/show_all_less_buttons.js, cypress/integration/view_options.spec.js
1.  Add waiting time after update
2. Add missing `;`
1. pull PR and do local cypress test
2. check the preview deploy
=> update test cases

cypress/integration/additional_pages.spec.js, cypress/integration/admin_homepage_sponsors_config.spec.js, cypress/integration/admin_homepage_top_config.spec.js, cypress/integration/admin_page_contact_config.spec.js, cypress/integration/admin_page_searchfacets_config.spec.js, cypress/integration/admin_page_sitepages_config.spec.js, cypress/integration/admin_page_title_config.spec.js, cypress/integration/admin_page_upload_file.spec.js, cypress/integration/archive_metadata_display.spec.js, cypress/integration/authenticator_spec.js, cypress/integration/browse_collections.spec.js, cypress/integration/collection_metadata_display.spec.js, cypress/integration/language_config.spec.js, cypress/integration/linked_metadata.spec.js, cypress/integration/search_facet.spec.js, cypress/integration/view_options.spec.js, src/pages/admin/BrowseCollectionsForm.js
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2387) (:star:)
Use timeout instead of timewait for Cypress tests. It is a better practice.
- Pull and local test
- Check preview deployment 
Tag (@tingtingjh ) interested parties
=> Use timeout instead of timewait

cypress/integration/admin_displayed_attributes_config.spec.js, src/css/adminForms.css, src/lib/fetchTools.js, src/pages/admin/DisplayedAttributesForm.js, src/pages/admin/SiteAdmin.js, src/pages/admin/SitePagesForm.js
**Adds admin add/edit/delete functionality for displayed attributes.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2337) (:star:)
Adds admin add/edit/delete functionality for displayed attributes
* Adds form so that displayed attributes for a site can be edited by site admins
* Adds view so that displayed attributes can be reviewed
* Visit `/siteAdmin`
* Click "Displayed Attributes"
* Click "Edit"
* Modify an attribute field and click "Update Attributes" at the bottom.
* On the view page, check that the modification was applied
* Go back to the edit page and click "Delete Attribute" to remove a record and click "Update Attributes" at the bottom.
* On the view page, check that the …
=> Adds admin add/edit/delete functionality for displayed attributes

src/css/SiteAdmin.css, src/pages/admin/BrowseCollectionsForm.js, src/pages/admin/ContentUpload.js, src/pages/admin/DisplayedAttributesForm.js, src/pages/admin/HomepageForm.js, src/pages/admin/SearchFacetsForm.js, src/pages/admin/SiteAdmin.js, src/pages/admin/SiteForm.js, src/pages/admin/SitePagesForm.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2375
*see WordPress screen shot in https://webapps.es.vt.edu/jira/browse/LIBTD-2309
Creates 2 column layout with menu in sidebar and content panel to the right.
-Consistent presentation for "edit" and "view" radio buttons
-Moves sign out button to sidebar
-Changes NavLink to Link because the additional ARIA and active attributes generated with NavLink were problematic (all links showing current and active since they all link to the same page)
-Active link is highlighted
-Adds CSS
Click each link in the side menu and switch between "edit" and "view" to check that the layout is the same for every page. The page should not reload when menu links are clicked; instead the content to the right will change. Active link …
=> Basic layout for admin site

cypress/integration/admin_media_section_config.spec.js, src/pages/HomePage.js, src/pages/admin/MediaSectionForm.js, src/pages/admin/SiteAdmin.js
**The title of this pull-request should be a brief description of what the pull-request fixes/improves/changes. Ideally 50 characters or less.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2343) (:star:)
Adds config functionality for homepage media section
* Adds form page for homepage media section
*Adds view page to display homepage media section values
* visit "/siteAdmin"
* click "Homepage media section in left column"
* Check that values are displayed.
* Click "Edit" radio button at top
* Change a value in the form and submit
* Check that the value was successfully updated
* Click "Edit" again and change the value back
* Check that the value was successfully updated again
Any …
=> Adds config functionality for homepage media section

cypress/integration/archive_media_views.spec.js, package-lock.json, package.json, src/css/ArchivePage.css, src/pages/archives/ArchivePage.js
**Adds support for 3d object renders.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2381) (:star:)
Adds support for 3d object renders.
* checks if `manifest_url` is a .OBJ file
* If so it renders the file using the react-3d-viewer plugin
https://dwqdaiwenqi.github.io/react-3d-viewer/site/#/OBJ
* Install react-3d-viewer by running `npm install react-3d-viewer`
* Visit `/archive/cz94zm9p`
* Check that the 3d model is rendering and that you can interact with it (scroll, zoom).
* branch `LIBTD-2381`
@yinlinchen 
=> Adds support for 3d object renders

src/pages/collections/SubCollectionsLoader.js
Ask discussed in 12/14 DLD meeting, change label to `Collection Organization`. See [mockup](https://xd.adobe.com/view/02fc158b-3aaa-4619-671b-65852af58b64-74cd/screen/a34c7589-09ee-4b86-9c16-7b60e9bc64ba/). 
Tag (@VTUL/dld-dev @jimtuttle @soumikgh ) interested parties
=> Collection Organization

README.md, cypress/integration/admin_homepage_top_config.spec.js
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2400) (:star:)
Adjust the timeout for the `Update Homepage fields and revert` and update the readme
Add testing account information in the readme
1. pull the PR and do local test, all tests should pass
2. see deployment in the Amplfiy preview
Tag (@tingtingjh ) interested parties
=> adjust and add timeout

public/css/root.css, public/index.html, src/components/Header.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2372
Updates the header to match the current branding for the university.
Replaces previous header template code with the new code. This changes the logo in the header and changes the first link in the nav menu when expanded. Otherwise everything functions pretty much the same as before. There are also some changes for accessibility included in the new code, but those changes are invisible.
Header should show VT logo followed by "university libraries" in the header at all screen sizes. "University libraries" should be the first link in the nav menu when expanded.
branch is LIBTD-2372
@yinlinchen 
=> Updated header to match current university branding

public/index.html, src/components/Footer.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2405
Removes hardcoded footer html and replaces it with a web component.
Added scripts needed for web component to index.html and added custom element tag to footer component.
The footer should look and act the same as before. Check that it appears on each page and that it still responds correctly to different screen sizes.
Branch is LIBTD-2405
@yinlinchen 
=> Web component in footer

cypress/integration/podcast_deposit.spec.js, src/components/FileUploadField.js, src/components/FormFields.js, src/components/PodcastMediaElement.js, src/components/Thumbnail.js, src/lib/fetchTools.js, src/pages/admin/PodcastDeposit.js, src/pages/collections/CollectionItemsList.js
**Add file characterization for podcast audio files.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2102) (:star:)
Add file characterization for podcast audio files.
* Gets name, type, and size (bytes) from File object
* Creates Audio object from file to get duration (time)
* Go to "/podcastDeposit" page
* Fill in values for all fields
* Upload an audio file (there is a test file you can use at `cypress/fixtures/sitecontent/audioFile.wav`)
* Submit the form
* On the page you're taken to you should see "Podcast entry successfully created"
* Check to make sure that the file details show up under "manifest_file_characterization:"
* branch: `LIBTD-2102_content`
@yinlinchen 
(:star:) …
=> Add file characterization for podcast audio files.

src/components/MiradorViewer.js
**Refresh mirador viewer on componentUpdate if manifest_url changes so that the image will be correct for related items.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2440) (:star:)
Refresh mirador viewer on componentUpdate if manifest_url changes so that the image will be correct for related items.
* Adds `componentDidUpdate` method to MiradorViewer.js
* Visit an archive page that uses Mirador Viewer to display content
* Click on a Related Item and check to make sure that the Mirador Viewer updates to the correct image.
Example:
* branch: `LIBTD-2440`
@yinlinchen 
=> Refresh mirador viewer on componentUpdate

src/lib/MetadataRenderer.js
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2474) (:star:)
This is a quick fix to convert HTML string. 
Original:
To:
1. Update any Collection or Archive description with a HTML string. e.g. 
```
<a href=\"https://vt.edu/\">VT</a>
``` 
It will convert the HTML string. e.g. In a archive page
=> Conver HTML string

src/pages/admin/SearchPageForm.js
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2490) (:star:)
Make date range search optional
From:
To:
1. Pull the branch
2. Delete `facet field: date`
3. Add `facet field: date` value back 
Tag (@whunter ) interested parties
=> make date range search optional

src/components/Citation.js, src/components/PodcastMediaElement.js, src/lib/MetadataRenderer.js, src/pages/admin/SiteForm.js, src/pages/archives/ArchivePage.js, src/pages/collections/CollectionsShowPage.js, src/pages/search/ItemListView.js
**Make redirectURL configurable in site form and adjust render code to use variable.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2452) (:star:)
Make redirectURL configurable in site form and adjust render code to use variable.
* Add redirectURL to site form so that it can be configured
* Refactor Citation and metadata renderer to use variable with fallback to previous value.
* Visit /siteAdmin and click the Edit radio button on General Site Config.
* Add your url to the Redirection URL field and click "Update Site"
* Visit an Archive show page and check the Citation field to see if the redirectURL is being rendered
* branch: `LIBTD-2452`
@yinlinchen 
=> add redirectURL to site form

public/js/one.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2504
I missed some parts in the one.js that needed updated. This was causing some problems with the scrolling of the site. This PR will fix that.
one.js
Scrolling should be enabled when navigation menu is closed and disabled when it is open.
Branch is LIBTD-2504fix
@yinlinchen 
=> Fixed scrolling

public/google254643b47916eed1.html
**Adds google verification file to public directory.**
* * *
Adds google verification file to public directory.
* Adds google verification file to public directory.
* visit `localhost:3000/google254643b47916eed1.html`
* Check that file renders correctly
* branch: `google_verification`
@yinlinchen 
=> add google verification file

src/App.js, src/css/HomePage.scss, src/css/adminForms.scss, src/css/colors.scss, src/pages/HomePage.js, src/pages/admin/HomepageForm.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2540
https://apps.es.vt.edu/confluence/display/LIBTD/2021-10-29+Meeting+notes
Adds style options for the user to choose from to customize the site's title on the homepage.
-Adds the other two VT branded fonts as options
-Allows custom font size
-Allows style options for uppercase, lowercase, capitalized or unstyled text.
App.js - adjusts function to set css variable for font size as well
homepage.scss - adjusts css
adminForms.scss - adds necessary css for admin form
colors.scss - adds font size css variable
HomePage.js - adds function to get style object
HomepageForm.js - adds form to set new properties for title font, font size and …
=> Customizations for site title font, font size, and text style

src/pages/admin/ArchiveCollectionEdit/CollectionForm.js, src/pages/admin/PodcastDeposit.js
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2543) (:star:)
1. Use Noid as identifier for collection
2. Use <Noid><series/season><episode#> e.g. cg58wz0w001001 for podcast archive item
Update "source_link" and "source_text" to "Website text" and "Website link"
1. Pull and test locally
2. See Amplify preview
Tag (@whunter ) interested parties
=> Use Noid, replace uuid for identifier

src/pages/admin/ArchiveCollectionEdit/CollectionForm.js
**Updates collectionmap.title on collection.title edit. Creates collectionMap record when new collection is created.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2481) (:star:)
Updates collectionmap.title on collection.title edit. Creates collectionMap record when new collection is created.
Updates collectionmap.title on collection.title edit. Creates collectionMap record when new collection is created.
* Update the title of a collection and check that the title in the collection tree updates to match.
* Create a new collection and check that a corresponding collectionMap is created
* branch: `LIBTD-2481`
@yinlinchen 
=> Updates collectionmap.title on collection.title edit

cypress/integration/richSchemaTools.spec.js, src/lib/richSchemaTools.js, src/pages/archives/ArchivePage.js, src/pages/collections/CollectionsShowPage.js
**JIRA Ticket**: ([link](https://webapps.es.vt.edu/jira/browse/LIBTD-2570)) (:star:)
1. Add Podcast JSON-LD schema into collection and archive pages
2. Test cases
1. See preview in amplify console
2. Inspect the page source, you should see there is a `<script type="application/ld+json" data-react-helmet="true">....</script>` in the `<header>...</header>` section
Tag (@whunter ) interested parties
=> add podcast rich schmea

src/lib/richSchemaTools.js, src/pages/archives/ArchivePage.js, src/pages/collections/CollectionsShowPage.js
**JIRA Ticket**: ([link](https://webapps.es.vt.edu/jira/browse/LIBTD-2574)) (:star:)
1. Complete remain podcast rich schema: webFeed and duration
1. Pull the branch and start the app using `REACT_APP_REP_TYPE=podcasts`
2. Check MFAngle collection and its episodes. The complete rich schema are in the `<header>` section.  
Tag (@whunter ) interested parties
=> Complete podcast rich schema

src/components/PodcastMediaElement.js, src/css/podcastMediaElement.scss
https://webapps.es.vt.edu/jira/browse/LIBTD-2558
Allows mediaelement.js player to display.
Changes order in which the file and player load. Also updates styles for better alignment.
-go to a podcast episode and the stylized player (black bar) should show instead of the native html player.
Branch is LIBTD-2558
@yinlinchen 
=> Fixed media player

src/pages/admin/ArchiveCollectionEdit/ArchiveForm.js
**Adds visibility to update item form so that it can be modified.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2568) (:star:)
Adds visibility to update item form so that it can be modified.
* Adds visibility to `displayedAttributes` in DynamoDB Site records.
* Adds visibility to Archive form as a checkbox (boolean)
* Adds visibility to View template so it's value will be displayed
* Toggle the visibility of an Archive record (checkbox at the very bottom)
* Check that the Archive renders (or doesn't) appropriately on "View All Items" page and it's Archive "Show" page
* Don't forget to make it visible again when you're done :)
* branch: `LIBTD-2568`
@yinlinchen 
=> Adds visibility to update item form so that it can be modified.

amplify/team-provider-info.json
This is the "dlppprd" backend environment details from the PPRD Amplify app "dlp".  It was suggested in the last meeting that these be consolidated all in one place in DEV.
=> Add "dlppprd" environment from PPRD

package-lock.json
**JIRA Ticket**: ([link](https://webapps.es.vt.edu/jira/browse/LIBTD-2583)) (:star:)
Patch security vulnerabilities, address #326 #325 #324 #317 #310 #309
=> patch security vulnerabilities

package-lock.json, package.json
=> replace node-sass

cypress/integration/related_items.spec.js
**switch tests to be.visible and use timeout instead of wait.**
* * *
switch tests to be.visible and use timeout instead of wait
* use be.visible instead of checking for class
* use long timeout instead of wait
* run the tests
* branch: `fix_related_items_tests`
@yinlinchen 
=> switch tests to be.visible and use timeout instead of wait

src/pages/admin/ArchiveCollectionEdit/ArchiveForm.js, src/pages/admin/ArchiveCollectionEdit/IdentifierForm.js
**Allows deletion of Archive records.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2589) (:star:)
* Allows deletion of Archive records.
* Add "Delete Item" button to Archive Form
* Add query to delete record from Dynamo
* Add function to reset Identifier Form to clear out the deleted record's identifier
* Start Podcast site
* Click "Add Podcast Episode" on siteAdmin page
* Create a podcast record. (take note of the generated identifier)
* Click on "Update Item" tab on siteAdmin page.
* Search using the generated identifier from the created record
* Scroll to the bottom of the page and click "Delete Item" and then click "OK" in the confirmation dialog
* Check that the record has been …
=> allow archive deletion

src/components/CollectionMetadataSection.js, src/components/SocialButtons.js, src/pages/collections/CollectionItemsList.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2559
I missed a few places that used the viewOption value to triggered certain styles in the list view. This PR updates those to check for the correct value.
Changes listView to list, which is the value that the admin site sets.
The list view in the collection pages should look correct now.
branch is fixListView
@yinlinchen 
=> Fixes listView

src/css/adminForms.scss, src/lib/fetchTools.js, src/pages/admin/ArchiveCollectionEdit/ArchiveForm.js, src/pages/admin/ArchiveCollectionEdit/IdentifierForm.js, src/pages/admin/SiteAdmin.js
**Create an item (Archive) for a Collection through admin interface.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2396) (:star:)
Allows admin users to create an item (Archive) for a Collection through admin interface.
* Allows access to Item form without an identifier
* Allows user to select collection for the new Item
* Creates id, identifier, and permanent link for the record
* Creates Archive record in DynamoDB
* Visit "/siteAdmin" page
* Click on the New/Update Item tab in the left column
* Click "Edit" to go to the form
* Fill out all required fields
* Click "Update Item Metadata"
* Check that record was successfully created
* branch: `LIBTD-2396`
@yinlinchen 
(:star:) Required …
=> Create an item (Archive) for a Collection through admin interface

README.md, docs/deploy.md, examples/amplify.yml, examples/jsons/DynamoDB_JSON/archive_item1.json, examples/jsons/DynamoDB_JSON/archive_item2.json, examples/jsons/DynamoDB_JSON/archive_item3.json, examples/jsons/DynamoDB_JSON/archive_item4.json, examples/jsons/DynamoDB_JSON/archive_item5.json, examples/jsons/DynamoDB_JSON/archive_item6.json, examples/jsons/DynamoDB_JSON/archive_item7.json, examples/jsons/DynamoDB_JSON/archive_item8.json, examples/jsons/DynamoDB_JSON/democollection.json, examples/jsons/DynamoDB_JSON/democollectionmap.json, examples/jsons/DynamoDB_JSON/site.json, examples/jsons/archive_item1.json, examples/jsons/archive_item2.json, examples/jsons/archive_item3.json, examples/jsons/archive_item4.json, examples/jsons/archive_item5.json, examples/jsons/archive_item6.json, examples/jsons/archive_item7.json, examples/jsons/archive_item8.json, examples/jsons/democollection.json, examples/jsons/democollectionmap.json, examples/jsons/site.json
**JIRA Ticket**: ([link](https://webapps.es.vt.edu/jira/browse/LIBTD-2591)) (:star:)
Update readme to the latest version.
=> Readme update

amplify/backend/auth/iawav2658176f3/iawav2658176f3-cloudformation-template.yml, amplify/backend/auth/userPoolGroups/template.json, amplify/backend/function/iawav2658176f3PostConfirmation/iawav2658176f3PostConfirmation-cloudformation-template.json, amplify/backend/function/iawav2658176f3PostConfirmation/src/package-lock.json, amplify/backend/storage/Collectionmap/s3-cloudformation-template.json, amplify/cli.json, amplify/team-provider-info.json, src/graphql/schema.json
**New backend with correct field mappings in search indices.**
* * *
New backend with correct field mappings in search indices.
* Adds dlpdev backend with more complete search indices
* Pull dlpdev application branch
* Checkout dlpdev backend environment
* Run tests
* Do visual check to see that the application is working as expected
Example:
* application branch: `dlpdev`
* backend env: `dlpdev`
@yinlinchen 
=> New backend with correct field mappings in search indices.

package-lock.json
**This PR updates some npm packages.**
* * *
**JIRA Ticket**: ([link](https://webapps.es.vt.edu/jira/browse/LIBTD-2616)) (:star:)
This PR updates some npm packages.
* This PR updates some npm packages.
* Tests are passing
* Preview here: https://minor-updates.djf1n0m63xbku.amplifyapp.com/
* branch: `minor_updates`
@yinlinchen 
=> Updates some packages

src/components/MiradorViewer.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2635
Updates Mirador viewer settings to remove the side panel
MiradorViewer.js
Images should not show a menu button to open the sidebar in the upper left hand corner.
branch is LIBTD-2635
@whunter 
=> Mirador viewer settings

.gitignore, amplify/backend/api/collectionarchives/schema.graphql, amplify/backend/auth/iawav2658176f3/iawav2658176f3-cloudformation-template.yml, amplify/backend/auth/userPoolGroups/template.json, amplify/backend/function/iawav2658176f3PostConfirmation/iawav2658176f3PostConfirmation-cloudformation-template.json, amplify/backend/function/iawav2658176f3PostConfirmation/src/package-lock.json, amplify/backend/storage/Collectionmap/s3-cloudformation-template.json, amplify/team-provider-info.json, cypress/integration/admin_archive_edit.spec.js, src/components/CollectionMetadataSection.js, src/components/CollectionTopContent.js, src/graphql/schema.json, src/lib/MetadataRenderer.js, src/lib/available_attributes.js, src/pages/admin/ArchiveCollectionEdit/ArchiveForm.js, src/pages/admin/ArchiveCollectionEdit/CollectionForm.js, src/pages/admin/ArchiveCollectionEdit/ViewMetadata.js, src/pages/admin/DisplayedAttributesForm.js, src/pages/archives/ArchivePage.js, src/pages/collections/CollectionsShowPage.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2637
Allows users to add multiple descriptions for items and collections in the admin interface, and add multiple labels for descriptions for both collections and archives. Also updates the interface to display multiple descriptions and headings.
**Note that descriptions must be in an array for these changes to work.
- src/components/CollectionMetadataSection.js - adds labels and filters out description from rendering in the table with all the other metadata.
- src/components/CollectionTopContent.js - updates getDescription() to work for array of descriptions.
- src/lib/MetadataRenderer.js - updates functions to work with array of …
=> Makes description multi-valued

cypress/integration/collection_metadata_display.spec.js, src/App.js, src/components/HeaderBreadcrumbs.js, src/css/adminForms.scss, src/lib/MetadataRenderer.js, src/pages/admin/ArchiveCollectionEdit/ArchiveForm.js, src/pages/admin/SiteAdmin.js, src/pages/admin/ingestTools/PreIngestCheck.js, src/pages/admin/ingestTools/PreIngestTable.js
**Creates interface to compare metadata file with directory of digital objects and produce report.**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2622) (:star:)
Creates interface to compare metadata file with directory of digital objects and produce report.
* Checks if metadata records are valid and contain required fields `Identifier`, `Title`
* Provides list of identifiers found in metadata file and the digital objects that are associated with them in the local directory
* Provides list of identifiers that DO NOT have any digital objects associated with them (likely in error)
This PR is …
=> Creates interface to compare metadata file with directory of dig objects.

cypress/integration/language_config.spec.js, cypress/integration/search_bar.spec.js, src/components/MediaElement.js, src/components/PodcastMediaElement.js, src/css/ArchivePage.scss, src/css/SearchResult.scss, src/lib/MetadataRenderer.js, src/lib/fetchTools.js, src/pages/AboutPage.js, src/pages/AdditionalPages.js, src/pages/PermissionsPage.js, src/pages/admin/HomepageForm.js, src/pages/archives/ArchivePage.js, src/pages/home/HomeStatement.js, src/pages/home/MultimediaSection.js, src/pages/search/GalleryView.js, src/pages/search/ItemListView.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2660
This PR ensures that all html content from the database is sanitized and parsed correctly so that html tags are displayed as html.
-MediaElement.js and PodcastMediaElement.js - Parses transcript html rather displaying in iframe. Also generates signed link for transcript download button when clicked so that link is not expired.
-MetadataRenderer.js - Adds cleanHTML() function and uses it within the other functions in this library which render html from the database.
-AboutPage.js, AdditionalPages.js, PermissionsPage.js, HomeStatement.js, HomepageForm.js, MultimediaSection.js - All components use the new cleanHTML function. …
=> Sanitize and display html

amplify/backend/function/iawav2658176f3PostConfirmation/iawav2658176f3PostConfirmation-cloudformation-template.json, amplify/backend/types/amplify-dependent-resources-ref.d.ts, cypress/integration/linked_metadata.spec.js, package-lock.json, package.json, public/index.html, src/components/MiradorViewer.js, src/graphql/schema.json, src/graphql/subscriptions.js, src/pages/search/GalleryView.js
**loads Mirador through component not from index.html**
* * *
**JIRA Ticket**: (https://webapps.es.vt.edu/jira/browse/LIBTD-2664) (:star:)
loads Mirador through component not from index.html
* load Mirador through component not from index.html
* addresses bug when multi-valued field (array) passed to cleanHTML()
* Visit an archive page and check that Mirador viewer loads correctly
Example:
* change_mirador_fetch
@andreaWaldren 
=> loads Mirador through component not from index.html

.prettierrc.json, src/App.js, src/css/NotFound.scss, src/pages/NotFound/NotFound.tsx, src/pages/NotFound/index.ts, src/pages/NotFound/not-found.test.js, src/pages/archives/ArchivePage.js, src/pages/collections/CollectionsShowPage.js, src/pages/home/FeaturedItems/FeaturedItems.tsx
https://webapps.es.vt.edu/jira/browse/LIBTD-2671
Adds a page to display when a user tries to access a url/item/collection that does not exist for the site.
-Adds a wildcard route to catch all non matching paths. Also returns the not found page if a custom key for an item or collection does not exist.
-Also adds a config file for prettier so we can start to standardize our settings.
Try to access an incorrect url within the demo site and the page should display a "Page Not Found" message. Also try to access the page for an archiv or collection that doesn't exist. It should also display a "Page not found" message.
branch is LIBTD-2671
@goynejennifer
=> 404 not found page

src/components/SearchBar.js, src/pages/HomePage.js, src/pages/search/SearchResults.js
https://webapps.es.vt.edu/jira/browse/LIBTD-2672
Fixes the search bar on the homepage so that search button takes user to the search results page.
Search bar component navigates to the correct page. Also updates props for the component
Type search terms into the search bar and click search. This should open the search page with the search results.
branch is searchFix
**just ignore all the formatting stuff that prettier changed.
@whunter 
=> Fixes homepage search

src/components/CheckboxSelector.js, src/components/FilterDropdown.js, src/components/ResultsNumberDropdown.js, src/components/SortOrderDropdown.js, src/components/SortbyDropdown.js, src/fixtures/mock_archive.ts, src/fixtures/mock_collection.ts, src/fixtures/mock_site.ts, src/index.js, src/lib/fetchTools.js, src/pages/collections/BrowseCollections/browse-collections.test.js, src/pages/collections/CollectionsShowPage/tests/collection-description.test.js, src/pages/collections/CollectionsShowPage/tests/collection-items.test.js, src/pages/collections/CollectionsShowPage/tests/collection-metadata-section.test.js, src/pages/collections/CollectionsShowPage/tests/collection-top-content.test.js, src/pages/collections/CollectionsShowPage/tests/collections-list-view.test.js, src/pages/collections/CollectionsShowPage/tests/collections-show-page.test.js, src/pages/collections/CollectionsShowPage/tests/rss-feeds.test.js, src/pages/collections/CollectionsShowPage/tests/subcollections-tree.test.js, src/pages/collections/CollectionsShowPage/useGetCollection.ts
https://webapps.es.vt.edu/jira/browse/LIBTD-2668
Adds unit tests for the refactored collection pages
Adds unit tests for collection pages and makes some needed changes for the unit tests: adds fixtures folder for mock files used in the tests, moves css import for semantic UI from components up to index.js file, and moves a custom query from a hook into our fetchTools file.
Pull the branch and run "npm test" then press "a" for all. They should all pass.
branch is LIBTD-2668-3tests
no preview generated
@whunter 
@goynejennifer 
=> Unit tests for collection pages
